from __future__ import annotations

NAMESPACE_DISCOVERY = {
    "core": {
        "client_map": {
            "virtual_network": "oci.core.VirtualNetworkClient",
            "compute": "oci.core.ComputeClient",
            "compute_management": "oci.core.ComputeManagementClient",
            "blockstorage": "oci.core.BlockstorageClient",
        },
        "endpoint_family": "iaas",
        "custom_listers": {
            "custom-images": "_list_custom_images",
            "vcns": "_list_vcns",
            "platform-images": "_list_platform_images",
            "route-rules": "_list_route_rules",
            "security-list-rules": "_list_security_list_rules",
            "subnets": "_list_subnets",
            "instances": "_list_instances",
            "ipv6s": "_list_ipv6s",
        },
        "node_capability_overrides": {
            "network_security_group_security_rules": "terminal-record-set",
            "route_rules": "terminal-record-set",
            "security_list_rules": "terminal-record-set",
        },
        "extra_specs": [
            {
                "name": "custom-images",
                "endpoint_family": "iaas",
                "scope": "compartment(filtered)",
                "lister_name": "_list_custom_images",
                "client_attr": "compute",
                "client_name": "ComputeClient",
                "list_operation": "list_images",
                "required_params": ("compartment_id",),
                "accepted_params": ("compartment_id",),
                "runnable": True,
            },
            {
                "name": "platform-images",
                "endpoint_family": "iaas",
                "scope": "regional-catalog",
                "lister_name": "_list_platform_images",
                "client_attr": "compute",
                "client_name": "ComputeClient",
                "list_operation": "list_images",
                "required_params": ("compartment_id",),
                "accepted_params": ("compartment_id",),
                "runnable": True,
            },
            {
                "name": "route-rules",
                "endpoint_family": "iaas",
                "scope": "parent-resource",
                "lister_name": "_list_route_rules",
                "client_attr": "virtual_network",
                "client_name": "VirtualNetworkClient",
                "list_operation": "get_route_table",
                "required_params": ("route_table_id",),
                "accepted_params": ("route_table_id",),
                "runnable": False,
                "findable": False,
                "node_capability": "terminal-record-set",
            },
            {
                "name": "security-list-rules",
                "endpoint_family": "iaas",
                "scope": "parent-resource",
                "lister_name": "_list_security_list_rules",
                "client_attr": "virtual_network",
                "client_name": "VirtualNetworkClient",
                "list_operation": "get_security_list",
                "required_params": ("security_list_id",),
                "accepted_params": ("security_list_id",),
                "runnable": False,
                "findable": False,
                "node_capability": "terminal-record-set",
            },
        ],
    },
    "containerengine": {
        "client_map": {
            "container_engine": "oci.container_engine.ContainerEngineClient",
        },
        "endpoint_family": "containerengine",
        "node_capability_overrides": {
            "addons": "metadata-record",
            "addon_options": "metadata-record",
        },
        "extra_specs": [
            {
                "name": "node-pool-options",
                "endpoint_family": "containerengine",
                "scope": "parent-resource",
                "lister_name": "_list_node_pool_options",
                "client_attr": "container_engine",
                "client_name": "ContainerEngineClient",
                "list_operation": "get_node_pool_options",
                "required_params": ("node_pool_option_id",),
                "accepted_params": ("node_pool_option_id",),
                "runnable": False,
                "findable": False,
                "node_capability": "terminal-record-set",
            },
        ],
    },
    "network_firewall": {
        "client_map": {
            "network_firewall": "oci.network_firewall.NetworkFirewallClient",
        },
        "endpoint_family": "network_firewall",
    },
    "generative_ai": {
        "client_map": {
            "generative_ai": "oci.generative_ai.GenerativeAiClient",
        },
        "endpoint_family": "generative_ai",
        "catalog_discovery": "direct",
        "openai_data": {
            "base_url": "https://inference.generativeai.{region}.oci.oraclecloud.com/openai/v1",
            "api_key_env": "OCISH_OCI_GENAI_API_KEY,OCI_GENAI_API_KEY",
            "max_pages": "20",
            "auth_error": "OCI OpenAI project data needs OCI IAM auth or an API key. Install oci-genai-auth, or set OCISH_OCI_GENAI_API_KEY.",
        },
        "resource_name_overrides": {"generative_ai_projects": "projects"},
        "extra_specs": [
            {
                "name": "project-files",
                "endpoint_family": "generative_ai_openai",
                "scope": "parent-resource",
                "lister_name": "_list_openai_project_data",
                "adapter_config": {"collection": "files", "project_param": "generative_ai_project_id"},
                "required_params": ("generative_ai_project_id",),
                "accepted_params": ("generative_ai_project_id",),
                "runnable": False,
                "findable": False,
            },
            {
                "name": "project-containers",
                "endpoint_family": "generative_ai_openai",
                "scope": "parent-resource",
                "lister_name": "_list_openai_project_data",
                "adapter_config": {"collection": "containers", "project_param": "generative_ai_project_id"},
                "required_params": ("generative_ai_project_id",),
                "accepted_params": ("generative_ai_project_id",),
                "runnable": False,
                "findable": False,
            },
            {
                "name": "project-vector-stores",
                "endpoint_family": "generative_ai_openai",
                "scope": "parent-resource",
                "lister_name": "_list_openai_project_data",
                "adapter_config": {"collection": "vector_stores", "project_param": "generative_ai_project_id"},
                "required_params": ("generative_ai_project_id",),
                "accepted_params": ("generative_ai_project_id",),
                "runnable": False,
                "findable": False,
            },
            {
                "name": "container-files",
                "endpoint_family": "generative_ai_openai",
                "scope": "parent-resource",
                "lister_name": "_list_openai_project_data",
                "adapter_config": {"collection": "containers.files", "project_param": "generative_ai_project_id", "parent_param": "container_id"},
                "required_params": ("container_id",),
                "accepted_params": ("container_id",),
                "runnable": False,
                "findable": False,
            },
            {
                "name": "vector-store-files",
                "endpoint_family": "generative_ai_openai",
                "scope": "parent-resource",
                "lister_name": "_list_openai_project_data",
                "adapter_config": {"collection": "vector_stores.files", "project_param": "generative_ai_project_id", "parent_param": "vector_store_id"},
                "required_params": ("vector_store_id",),
                "accepted_params": ("vector_store_id",),
                "runnable": False,
                "findable": False,
            },
        ],
    },
    "generative_ai_agent": {
        "client_map": {
            "generative_ai_agent": "oci.generative_ai_agent.GenerativeAiAgentClient",
        },
        "endpoint_family": "generative_ai_agent",
        "catalog_discovery": "direct",
    },
    "load_balancer": {
        "client_map": {
            "load_balancer": "oci.load_balancer.LoadBalancerClient",
        },
        "endpoint_family": "load_balancer",
        "custom_listers": {"listeners": "_list_load_balancer_listeners"},
        "extra_specs": [
            {
                "name": "listeners",
                "endpoint_family": "load_balancer",
                "scope": "parent-resource",
                "lister_name": "_list_load_balancer_listeners",
                "client_attr": "load_balancer",
                "client_name": "LoadBalancerClient",
                "list_operation": "get_load_balancer",
                "required_params": ("load_balancer_id",),
                "accepted_params": ("load_balancer_id",),
                "runnable": False,
                "findable": False,
            },
        ],
    },
    "logging": {
        "client_map": {
            "logging": "oci.logging.LoggingManagementClient",
        },
        "endpoint_family": "logging",
    },
    "audit": {
        "endpoint_family": "audit",
        "adapter_kind": "bounded-time-query",
        "extra_specs": [
            {
                "name": "events",
                "endpoint_family": "audit",
                "scope": "compartment(query)",
                "runnable": True,
                "findable": False,
            },
        ],
    },
    "monitoring": {
        "client_map": {"monitoring": "oci.monitoring.MonitoringClient"},
        "endpoint_family": "monitoring",
        "runnable_overrides": {"metrics": True},
        "findable_overrides": {"metrics": False},
    },
    "apm": {
        "client_map": {"apm_domain": "oci.apm_control_plane.ApmDomainClient"},
        "endpoint_family": "apm",
    },
    "log_analytics": {
        "client_map": {"log_analytics": "oci.log_analytics.LogAnalyticsClient"},
        "endpoint_family": "log_analytics",
        "extra_specs": [
            {
                "name": "queries",
                "endpoint_family": "log_analytics",
                "scope": "compartment(query)",
                "runnable": True,
                "findable": False,
            },
        ],
    },
    "object_storage": {
        "client_map": {"object_storage": "oci.object_storage.ObjectStorageClient"},
        "endpoint_family": "object_storage",
        "adapter_kind": "hierarchical-content",
        "custom_listers": {"buckets": "_list_object_storage_buckets"},
        "runnable_overrides": {"buckets": True},
        "findable_overrides": {"buckets": False},
    },
    "artifacts": {
        "client_map": {"artifacts": "oci.artifacts.ArtifactsClient"},
        "endpoint_family": "artifacts",
    },
    "devops": {
        "client_map": {"devops": "oci.devops.DevopsClient"},
        "endpoint_family": "devops",
        "runnable_overrides": {"repositories": True},
    },
    "dns": {
        "client_map": {
            "dns": "oci.dns.DnsClient",
        },
        "endpoint_family": "dns",
        "extra_specs": [
            {
                "name": "zone-records",
                "endpoint_family": "dns",
                "scope": "parent-resource",
                "lister_name": "_list_zone_records",
                "client_attr": "dns",
                "client_name": "DnsClient",
                "list_operation": "get_zone_records",
                "required_params": ("zone_name_or_id",),
                "accepted_params": ("zone_name_or_id",),
                "runnable": False,
                "findable": False,
            },
        ],
    },
    "identity": {
        "client_map": {
            "identity": "oci.identity.IdentityClient",
        },
        "endpoint_family": "identity",
        "custom_listers": {
            "compartments": "_list_compartment_rows",
            "region_subscriptions": "_list_region_subscriptions",
        },
        "scope_overrides": {
            "regions": "global",
            "region_subscriptions": "tenancy",
        },
        "runnable_overrides": {
            "region_subscriptions": True,
        },
        "findable_overrides": {
            "regions": False,
            "region_subscriptions": False,
        },
    },
    "limits": {
        "client_map": {"limits": "oci.limits.LimitsClient"},
        "endpoint_family": "limits",
        # Limits services are API metadata rather than OCI Search resources.
        # A service is navigable only to expose its definitions and values.
        "findable_overrides": {
            "services": False,
            "limit_definitions": False,
            "limit_values": False,
        },
        "node_capability_overrides": {
            "services": "metadata-record",
            "limit_definitions": "terminal-record-set",
            "limit_values": "terminal-record-set",
        },
    },
    "orm": {
        "client_map": {
            "resource_manager": "oci.resource_manager.ResourceManagerClient",
        },
        "endpoint_family": "orm",
        "custom_listers": {
            "jobs": "_list_orm_jobs",
            "terraform_versions": "_list_terraform_versions",
        },
        "scope_overrides": {
            "template_categories": "region",
        },
        "search_type_overrides": {
            "configuration_source_providers": "OrmConfigSourceProvider",
            "jobs": "OrmJob",
            "private_endpoints": "OrmPrivateEndpoint",
            "stacks": "OrmStack",
            "templates": "OrmTemplate",
        },
        "findable_overrides": {
            "terraform_versions": False,
            "template_categories": False,
        },
    },
}

# Public namespace path spelling.  SDK identifiers remain the internal keys;
# the default slug is hyphenated and the SDK spelling remains an accepted alias.
NAMESPACE_PATH_SLUGS = {
    namespace: namespace.replace("_", "-") for namespace in NAMESPACE_DISCOVERY
}

# Topology is a projection, never an ownership rewrite.  Each edge declares
# the exact source field, its role, and whether it is direct or derived.
TOPOLOGY_EDGES = {
    "network_firewall.network_firewalls": (
        {
            "field": "subnet_id",
            "target": "core.subnets",
            "role": "placement-subnet",
            "kind": "direct",
        },
    ),
    "core.instances": (
        {
            "field": "vnic-attachments",
            "target": "core.subnets",
            "role": "network-placement",
            "kind": "derived",
            "via": "core.vnic_attachments",
            "source_field": "instance_id",
            "target_field": "subnet_id",
        },
    ),
    "containerengine.clusters": (
        {
            "field": "endpoint_config.subnet_id",
            "target": "core.subnets",
            "role": "api-endpoint",
            "kind": "direct",
        },
    ),
    "load_balancer.load_balancers": (
        {
            "field": "subnet_ids",
            "target": "core.subnets",
            "role": "load-balancer",
            "kind": "direct",
        },
    ),
}

# Entry collections for ``<service>/topology``.  The navigator is generic;
# this registry only declares which canonical resource collections form a
# service's useful topology anchors.
TOPOLOGY_ROOTS = {
    "core": ("core.vcns",),
    "network_firewall": ("network_firewall.network_firewalls",),
    "containerengine": ("containerengine.clusters",),
    "load_balancer": ("load_balancer.load_balancers",),
}

# Virtual directories that structure every topology projection.  This is
# topology policy, not completion policy: consumers use it through the shell's
# generic topology-child resolver.
TOPOLOGY_STATIC_CHILDREN = {
    "root": ("vcns",),
    "vcn": ("subnets",),
    "subnet": ("consumers",),
}

RESOURCE_CONTEXT_DEFAULTS = {
    "core.app_catalog_listings": "app-catalog-listing-resource-versions",
    "core.byoip_ranges": "byoip-allocated-ranges",
    "core.cpes": "ip-sec-connections",
    "core.cluster_networks": "cluster-network-instances",
    "core.compute_capacity_reservations": "compute-capacity-reservation-instances",
    "core.compute_global_image_capability_schemas": "compute-global-image-capability-schema-versions",
    "core.compute_gpu_memory_clusters": "compute-gpu-memory-cluster-instances",
    "core.cross_connect_groups": "cross-connects",
    "core.dedicated_vm_hosts": "dedicated-vm-host-instances",
    "core.drg_route_distributions": "drg-route-distribution-statements",
    "core.drg_route_tables": "drg-route-rules",
    "core.images": "image-shape-compatibility-entries",
    "core.instance_pools": "instance-pool-instances",
    "core.ip_sec_connections": "ip-sec-connection-tunnels",
    "core.fast_connect_provider_services": "provider-remote-regions",
    "core.private_ips": "ipv6s",
    "core.route_tables": "route-rules",
    "core.subnets": "private-ips",
    "core.public_ip_pools": "public-ips",
    "core.volumes": "volume-backups",
    "core.boot_volumes": "boot-volume-backups",
    "core.volume_groups": "volume-group-backups",
    "core.volume_group_replicas": "block-volume-replicas",
    "containerengine.virtual-node-pools": "virtual-nodes",
    "dns.resolvers": "resolver-endpoints",
    "dns.zones": "zone-records",
    "identity.availability_domains": "fault-domains",
    "identity.groups": "user-group-memberships",
    "identity.iam_work_requests": "iam-work-request-logs",
    "identity.tag_namespaces": "tags",
    "identity.users": "user-group-memberships",
    "orm.jobs": "job-outputs",
    "orm.stacks": "jobs",
    "orm.work_requests": "work-request-logs",
}

RESOURCE_CONTEXT_CHILDREN = {
    "limits.services": {
        "definitions": (
            "limits.limit-definitions",
            (("service_name", "name"),),
            None,
        ),
        "values": (
            "limits.limit-values",
            (("service_name", "name"),),
            None,
        ),
    },
    "generative_ai.projects": {
        "files": (
            "generative_ai.project-files",
            (("generative_ai_project_id", "id"),),
            None,
        ),
        "containers": (
            "generative_ai.project-containers",
            (("generative_ai_project_id", "id"),),
            None,
        ),
        "vector-stores": (
            "generative_ai.project-vector-stores",
            (("generative_ai_project_id", "id"),),
            None,
        ),
    },
    "generative_ai.project_containers": {
        "files": (
            "generative_ai.container-files",
            (
                ("container_id", "id"),
                ("generative_ai_project_id", "generative_ai_project_id"),
            ),
            None,
        ),
    },
    "generative_ai.project_vector_stores": {
        "files": (
            "generative_ai.vector-store-files",
            (
                ("vector_store_id", "id"),
                ("generative_ai_project_id", "generative_ai_project_id"),
            ),
            None,
        ),
    },
    "generative_ai.vector_store_connectors": {
        "file-syncs": (
            "generative_ai.vector_store_connector_file_syncs",
            (("vector_store_connector_id", "id"),),
            None,
        ),
        "ingestion-logs": (
            "generative_ai.vector_store_connector_ingestion_logs",
            (("vector_store_connector_id", "id"),),
            None,
        ),
    },
    "generative_ai.vector_store_connector_file_syncs": {
        "ingestion-logs": (
            "generative_ai.vector_store_connector_file_sync_ingestion_logs",
            (("vector_store_connector_file_sync_id", "id"),),
            None,
        ),
    },
    "generative_ai.work_requests": {
        "work-request-errors": (
            "generative_ai.work_request_errors",
            (("work_request_id", "id"),),
            None,
        ),
        "work-request-logs": (
            "generative_ai.work_request_logs",
            (("work_request_id", "id"),),
            None,
        ),
    },
    "generative_ai_agent.agents": {
        "agent-endpoints": (
            "generative_ai_agent.agent_endpoints",
            (("agent_id", "id"),),
            None,
        ),
        "tools": (
            "generative_ai_agent.tools",
            (("agent_id", "id"),),
            None,
        ),
    },
    "generative_ai_agent.knowledge_bases": {
        "data-sources": (
            "generative_ai_agent.data_sources",
            (("knowledge_base_id", "id"),),
            None,
        ),
    },
    "generative_ai_agent.data_sources": {
        "data-ingestion-jobs": (
            "generative_ai_agent.data_ingestion_jobs",
            (("data_source_id", "id"),),
            None,
        ),
    },
    "generative_ai_agent.work_requests": {
        "work-request-errors": (
            "generative_ai_agent.work_request_errors",
            (("work_request_id", "id"),),
            None,
        ),
        "work-request-logs": (
            "generative_ai_agent.work_request_logs",
            (("work_request_id", "id"),),
            None,
        ),
    },
    "logging.log_groups": {
        "logs": ("logging.logs", (("log_group_id", "id"),), None),
    },
    "logging.work_requests": {
        "work-request-errors": (
            "logging.work_request_errors",
            (("work_request_id", "id"),),
            None,
        ),
        "work-request-logs": (
            "logging.work_request_logs",
            (("work_request_id", "id"),),
            None,
        ),
    },
    "load_balancer.load_balancers": {
        "backend-sets": (
            "load_balancer.backend_sets",
            (("load_balancer_id", "id"),),
            None,
        ),
        "certificates": (
            "load_balancer.certificates",
            (("load_balancer_id", "id"),),
            None,
        ),
        "hostnames": ("load_balancer.hostnames", (("load_balancer_id", "id"),), None),
        "listeners": ("load_balancer.listeners", (("load_balancer_id", "id"),), None),
        "path-route-sets": (
            "load_balancer.path_route_sets",
            (("load_balancer_id", "id"),),
            None,
        ),
        "routing-policies": (
            "load_balancer.routing_policies",
            (("load_balancer_id", "id"),),
            None,
        ),
        "rule-sets": ("load_balancer.rule_sets", (("load_balancer_id", "id"),), None),
        "ssl-cipher-suites": (
            "load_balancer.ssl_cipher_suites",
            (("load_balancer_id", "id"),),
            None,
        ),
        "work-requests": (
            "load_balancer.work_requests",
            (("load_balancer_id", "id"),),
            None,
        ),
    },
    "load_balancer.backend_sets": {
        "backends": (
            "load_balancer.backends",
            (("load_balancer_id", "load_balancer_id"), ("backend_set_name", "name")),
            None,
        ),
    },
    "load_balancer.listeners": {
        "listener-rules": (
            "load_balancer.listener_rules",
            (("load_balancer_id", "load_balancer_id"), ("listener_name", "name")),
            None,
        ),
    },
    "core.app_catalog_listings": {
        "app-catalog-listing-resource-versions": (
            "app-catalog-listing-resource-versions",
            (("listing_id", "id"),),
            None,
        ),
    },
    "core.byoip_ranges": {
        "byoip-allocated-ranges": (
            "byoip-allocated-ranges",
            (("byoip_range_id", "id"),),
            None,
        ),
        "public-ip-pools": ("public-ip-pools", (("byoip_range_id", "id"),), None),
    },
    "core.cpes": {
        "ip-sec-connections": ("ip-sec-connections", (("cpe_id", "id"),), None),
    },
    "core.cluster_networks": {
        "cluster-network-instances": (
            "cluster-network-instances",
            (("cluster_network_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
    },
    "core.cross_connect_groups": {
        "cross-connects": ("cross-connects", (("cross_connect_group_id", "id"),), None),
    },
    "core.compute_capacity_reservations": {
        "compute-capacity-reservation-instances": (
            "compute-capacity-reservation-instances",
            (("capacity_reservation_id", "id"),),
            None,
        ),
    },
    "core.compute_capacity_topologies": {
        "compute-capacity-topology-compute-bare-metal-hosts": (
            "compute-capacity-topology-compute-bare-metal-hosts",
            (("compute_capacity_topology_id", "id"),),
            None,
        ),
        "compute-capacity-topology-compute-hpc-islands": (
            "compute-capacity-topology-compute-hpc-islands",
            (("compute_capacity_topology_id", "id"),),
            None,
        ),
        "compute-capacity-topology-compute-network-blocks": (
            "compute-capacity-topology-compute-network-blocks",
            (("compute_capacity_topology_id", "id"),),
            None,
        ),
    },
    "core.compute_global_image_capability_schemas": {
        "compute-global-image-capability-schema-versions": (
            "compute-global-image-capability-schema-versions",
            (("compute_global_image_capability_schema_id", "id"),),
            None,
        ),
    },
    "core.compute_gpu_memory_clusters": {
        "compute-gpu-memory-cluster-instances": (
            "compute-gpu-memory-cluster-instances",
            (("compute_gpu_memory_cluster_id", "id"),),
            None,
        ),
    },
    "core.dedicated_vm_hosts": {
        "dedicated-vm-host-instances": (
            "dedicated-vm-host-instances",
            (("dedicated_vm_host_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
    },
    "core.drgs": {
        "drg-attachments": ("drg-attachments", (), "drg_id"),
        "ip-sec-connections": ("ip-sec-connections", (("drg_id", "id"),), None),
        "drg-route-distributions": (
            "drg-route-distributions",
            (("drg_id", "id"),),
            None,
        ),
        "drg-route-tables": ("drg-route-tables", (("drg_id", "id"),), None),
        "remote-peering-connections": (
            "remote-peering-connections",
            (("drg_id", "id"),),
            None,
        ),
    },
    "core.fast_connect_provider_services": {
        "provider-remote-regions": (
            "provider-remote-regions",
            (("provider_service_id", "id"),),
            None,
        ),
        "fast-connect-provider-virtual-circuit-bandwidth-shapes": (
            "fast-connect-provider-virtual-circuit-bandwidth-shapes",
            (("provider_service_id", "id"),),
            None,
        ),
    },
    "core.drg_route_distributions": {
        "drg-route-distribution-statements": (
            "drg-route-distribution-statements",
            (("drg_route_distribution_id", "id"),),
            None,
        ),
    },
    "core.drg_route_tables": {
        "drg-route-rules": ("drg-route-rules", (("drg_route_table_id", "id"),), None),
    },
    "core.images": {
        "image-shape-compatibility-entries": (
            "image-shape-compatibility-entries",
            (("image_id", "id"),),
            None,
        ),
    },
    "core.instances": {
        "boot-volume-attachments": (
            "boot-volume-attachments",
            (
                ("availability_domain", "availability_domain"),
                ("compartment_id", "compartment_id"),
            ),
            "instance_id",
        ),
        "instance-console-connections": (
            "instance-console-connections",
            (),
            "instance_id",
        ),
        "instance-devices": ("instance-devices", (("instance_id", "id"),), None),
        "vnic-attachments": ("vnic-attachments", (), "instance_id"),
        "volume-attachments": ("volume-attachments", (), "instance_id"),
    },
    "core.volumes": {
        "volume-backups": ("volume-backups", (("volume_id", "id"),), None),
    },
    "core.boot_volumes": {
        "boot-volume-backups": (
            "boot-volume-backups",
            (("boot_volume_id", "id"),),
            None,
        ),
    },
    "core.volume_groups": {
        "volume-group-backups": (
            "volume-group-backups",
            (("volume_group_id", "id"),),
            None,
        ),
    },
    "core.volume_group_replicas": {
        "block-volume-replicas": (
            "block-volume-replicas",
            (("volume_group_replica_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
        "boot-volume-replicas": (
            "boot-volume-replicas",
            (("volume_group_replica_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
    },
    "core.instance_pools": {
        "instance-pool-instances": (
            "instance-pool-instances",
            (("instance_pool_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
    },
    "core.ip_sec_connections": {
        "ip-sec-connection-tunnels": (
            "ip-sec-connection-tunnels",
            (("ipsc_id", "id"),),
            None,
        ),
    },
    "core.ip_sec_connection_tunnels": {
        "ip-sec-connection-tunnel-routes": (
            "ip-sec-connection-tunnel-routes",
            (("ipsc_id", "ipsc_id"), ("tunnel_id", "id")),
            None,
        ),
        "ip-sec-connection-tunnel-security-associations": (
            "ip-sec-connection-tunnel-security-associations",
            (("ipsc_id", "ipsc_id"), ("tunnel_id", "id")),
            None,
        ),
    },
    "core.network_security_groups": {
        "security-rules": (
            "network-security-group-security-rules",
            (("network_security_group_id", "id"),),
            None,
        ),
        "vnics": (
            "network-security-group-vnics",
            (("network_security_group_id", "id"),),
            None,
        ),
    },
    "core.private_ips": {
        "ipv6s": ("ipv6s", (("vnic_id", "vnic_id"),), None),
    },
    "core.public_ip_pools": {
        "public-ips": ("public-ips", (("public_ip_pool_id", "id"),), None),
    },
    "core.route_tables": {
        "route-rules": ("core.route-rules", (("route_table_id", "id"),), None),
    },
    "core.security_lists": {
        "security-list-rules": (
            "core.security-list-rules",
            (("security_list_id", "id"),),
            None,
        ),
    },
    "core.vcns": {
        "dhcp-options": ("dhcp-options", (("vcn_id", "id"),), None),
        "subnets": ("subnets", (("vcn_id", "id"),), None),
        "route-tables": ("route-tables", (("vcn_id", "id"),), None),
        "security-lists": ("security-lists", (("vcn_id", "id"),), None),
        "internet-gateways": ("internet-gateways", (("vcn_id", "id"),), None),
        "nat-gateways": ("nat-gateways", (("vcn_id", "id"),), None),
        "service-gateways": ("service-gateways", (("vcn_id", "id"),), None),
        "local-peering-gateways": ("local-peering-gateways", (("vcn_id", "id"),), None),
        "network-security-groups": (
            "network-security-groups",
            (("vcn_id", "id"),),
            None,
        ),
        "drg-attachments": ("drg-attachments", (("vcn_id", "id"),), None),
        "vlans": ("vlans", (("vcn_id", "id"),), None),
    },
    "core.subnets": {
        "private-ips": ("private-ips", (("subnet_id", "id"),), None),
        "ipv6s": ("ipv6s", (("subnet_id", "id"),), None),
    },
    "network_firewall.network_firewall_policies": {
        "address-lists": (
            "address-lists",
            (("network_firewall_policy_id", "id"),),
            None,
        ),
        "application-groups": (
            "application-groups",
            (("network_firewall_policy_id", "id"),),
            None,
        ),
        "applications": ("applications", (("network_firewall_policy_id", "id"),), None),
        "decryption-profiles": (
            "decryption-profiles",
            (("network_firewall_policy_id", "id"),),
            None,
        ),
        "decryption-rules": (
            "decryption-rules",
            (("network_firewall_policy_id", "id"),),
            None,
        ),
        "mapped-secrets": (
            "mapped-secrets",
            (("network_firewall_policy_id", "id"),),
            None,
        ),
        "nat-rules": ("nat-rules", (("network_firewall_policy_id", "id"),), None),
        "security-rules": (
            "security-rules",
            (("network_firewall_policy_id", "id"),),
            None,
        ),
        "service-lists": (
            "service-lists",
            (("network_firewall_policy_id", "id"),),
            None,
        ),
        "services": ("services", (("network_firewall_policy_id", "id"),), None),
        "tunnel-inspection-rules": (
            "tunnel-inspection-rules",
            (("network_firewall_policy_id", "id"),),
            None,
        ),
        "url-lists": ("url-lists", (("network_firewall_policy_id", "id"),), None),
    },
    "network_firewall.work_requests": {
        "work-request-errors": (
            "work-request-errors",
            (("work_request_id", "id"),),
            None,
        ),
        "work-request-logs": ("work-request-logs", (("work_request_id", "id"),), None),
    },
    "core.virtual_circuits": {
        "cross-connect-mappings": (
            "cross-connect-mappings",
            (("virtual_circuit_id", "id"),),
            None,
        ),
        "virtual-circuit-associated-tunnels": (
            "virtual-circuit-associated-tunnels",
            (("virtual_circuit_id", "id"),),
            None,
        ),
        "virtual-circuit-public-prefixes": (
            "virtual-circuit-public-prefixes",
            (("virtual_circuit_id", "id"),),
            None,
        ),
    },
    "containerengine.clusters": {
        "work-requests": (
            "containerengine.work-requests",
            (("cluster_id", "id"),),
            None,
        ),
        "addon-options": (
            "containerengine.addon-options",
            (("kubernetes_version", "kubernetes_version"),),
            None,
        ),
        "addons": ("containerengine.addons", (("cluster_id", "id"),), None),
        "pod-shapes": (
            "containerengine.pod-shapes",
            (("compartment_id", "compartment_id"),),
            None,
        ),
        "workload-mappings": (
            "containerengine.workload-mappings",
            (("cluster_id", "id"),),
            None,
        ),
        "node-pools": ("containerengine.node-pools", (), "cluster_id"),
        "node-pool-options": (
            "containerengine.node-pool-options",
            (("node_pool_option_id", "id"),),
            None,
        ),
        "virtual-node-pools": ("containerengine.virtual-node-pools", (), "cluster_id"),
    },
    "containerengine.virtual-node-pools": {
        "virtual-nodes": (
            "containerengine.virtual-nodes",
            (("virtual_node_pool_id", "id"),),
            None,
        ),
    },
    "containerengine.work-requests": {
        "work-request-errors": (
            "containerengine.work-request-errors",
            (("work_request_id", "id"),),
            None,
        ),
        "work-request-logs": (
            "containerengine.work-request-logs",
            (("work_request_id", "id"),),
            None,
        ),
    },
    "dns.resolvers": {
        "resolver-endpoints": (
            "dns.resolver-endpoints",
            (("resolver_id", "id"),),
            None,
        ),
    },
    "dns.zones": {
        "zone-records": ("dns.zone-records", (("zone_name_or_id", "id"),), None),
    },
    "identity.availability_domains": {
        "fault-domains": (
            "identity.fault-domains",
            (("compartment_id", "compartment_id"), ("availability_domain", "name")),
            None,
        ),
    },
    "identity.groups": {
        "user-group-memberships": (
            "identity.user-group-memberships",
            (("group_id", "id"),),
            None,
        ),
    },
    "identity.iam_work_requests": {
        "iam-work-request-errors": (
            "identity.iam-work-request-errors",
            (("iam_work_request_id", "id"),),
            None,
        ),
        "iam-work-request-logs": (
            "identity.iam-work-request-logs",
            (("iam_work_request_id", "id"),),
            None,
        ),
    },
    "identity.tag_namespaces": {
        "tags": ("identity.tags", (("tag_namespace_id", "id"),), None),
    },
    "identity.users": {
        "api-keys": ("identity.api-keys", (("user_id", "id"),), None),
        "auth-tokens": ("identity.auth-tokens", (("user_id", "id"),), None),
        "customer-secret-keys": (
            "identity.customer-secret-keys",
            (("user_id", "id"),),
            None,
        ),
        "db-credentials": ("identity.db-credentials", (("user_id", "id"),), None),
        "mfa-totp-devices": ("identity.mfa-totp-devices", (("user_id", "id"),), None),
        "o-auth-client-credentials": (
            "identity.o-auth-client-credentials",
            (("user_id", "id"),),
            None,
        ),
        "smtp-credentials": ("identity.smtp-credentials", (("user_id", "id"),), None),
        "swift-passwords": ("identity.swift-passwords", (("user_id", "id"),), None),
        "user-group-memberships": (
            "identity.user-group-memberships",
            (("user_id", "id"),),
            None,
        ),
    },
    "orm.stacks": {
        "jobs": ("orm.jobs", (("stack_id", "id"),), None),
        "stack-associated-resources": (
            "orm.stack-associated-resources",
            (("stack_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
        "stack-resource-drift-details": (
            "orm.stack-resource-drift-details",
            (("stack_id", "id"),),
            None,
        ),
    },
    "orm.jobs": {
        "job-associated-resources": (
            "orm.job-associated-resources",
            (("job_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
        "job-outputs": (
            "orm.job-outputs",
            (("job_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
    },
    "orm.work_requests": {
        "work-request-errors": (
            "orm.work-request-errors",
            (("work_request_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
        "work-request-logs": (
            "orm.work-request-logs",
            (("work_request_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
    },
    "artifacts.repositories": {
        "generic-artifacts": (
            "artifacts.generic-artifacts",
            (("repository_id", "id"), ("compartment_id", "compartment_id")),
            None,
        ),
    },
    "devops.projects": {
        "repositories": (
            "devops.repositories",
            (("project_id", "id"),),
            None,
        ),
    },
}

# Declarative virtual namespace behavior.  Engines interpret these rules; they
# must not embed resource-name checks for navigation or presentation behavior.
RESOURCE_VIRTUAL_CHILDREN = {
    "default": {"logs": {"kind": "related-logs", "resource_type": "logging.logs"}},
    "logging.logs": {
        "logs": None,
        "entries": {"kind": "time-query", "provider": "logging"},
    },
    "apm.apm_domains": {"query": {"kind": "time-query", "provider": "apm"}},
    "object_storage.buckets": {
        "objects": {"kind": "object-prefixes", "requires_absent_detail": "object_name"},
        "content": {"kind": "object-content", "requires_detail": "object_name"},
    },
}

ROOT_COLLECTION_VIEWS = {
    "logging.log_groups": {"kind": "tenancy-log-groups"},
    "audit.events": {"kind": "time-query", "provider": "audit"},
    "monitoring.metrics": {"kind": "time-query", "provider": "monitoring"},
    "log_analytics.queries": {"kind": "time-query", "provider": "log-analytics"},
}

# Provider declarations select the common time/query filesystem adapter.  The
# adapter owns navigation, control files, validation, pages and raw records;
# providers own only their OCI request/response translation.
TIME_QUERY_PROVIDERS = {
    "logging": {"controls": ("since", "until", "contains", "where"), "max_pages": 20},
    "audit": {"controls": ("since", "until"), "max_pages": 20},
    "monitoring": {
        "controls": ("query", "namespace", "since", "until", "resolution"),
        "max_pages": 1,
    },
    "apm": {"controls": ("query", "since", "until"), "max_pages": 20},
    "log-analytics": {"controls": ("query", "since", "until"), "max_pages": 20},
}

COMPARTMENT_COLLECTIONS = frozenset({"identity.compartments"})

RELATIONSHIP_PROVENANCE_RULES = {
    "containerengine.clusters": (
        {
            "source_label": "created-by-work-request",
            "label": "creation-work-request",
            "resource_type": "containerengine.work-requests",
            "api_kwargs": (("cluster_id", "id"),),
        },
    ),
}

INDIRECT_RELATIONSHIP_POLICIES = {
    "core.instances": {
        "child_collections": ("vnic-attachments",),
        "max_child_collections": 1,
    },
    "core.network_security_groups": {
        "child_collections": ("security-rules",),
        "max_child_collections": 1,
        "include_same_type": True,
    },
}

RESOURCE_ENRICHMENTS = {
    "load_balancer.load_balancers": (
        {
            "client_attr": "load_balancer",
            "getter": "get_load_balancer_health",
            "detail": "overall_health",
            "response_attr": "status",
            "fallback": "-",
            "delay_seconds": 0.1,
        },
    ),
}

LONG_COLUMNS = {
    "limits.services": [
        ("name", "Service"),
        ("description", "Description"),
    ],
    "limits.limit_definitions": [
        ("name", "Limit"),
        ("scope_type", "Scope"),
        ("are_quotas_supported", "Quotas"),
        ("is_eligible_for_limit_increase", "Increase eligible"),
        ("description", "Description"),
    ],
    "limits.limit_values": [
        ("name", "Limit"),
        ("value", "Value"),
        ("scope_type", "Scope"),
        ("availability_domain", "Availability domain"),
    ],
    "core.instances": [
        ("name", "Name"),
        ("state", "State"),
        ("private_ip", "Private IP"),
        ("public_ip", "Public IP"),
        ("shape", "Shape"),
        ("ocpus", "OCPU"),
        ("memory_gb", "Memory(GB)"),
        ("availability_domain", "Availability domain"),
        ("created", "Created"),
    ],
    "core.vcns": [
        ("name", "Name"),
        ("state", "State"),
        ("cidr", "CIDR"),
        ("dns_label", "DNS label"),
        ("is_ipv6_enabled", "IPv6"),
        ("created", "Created"),
    ],
    "core.subnets": [
        ("name", "Name"),
        ("state", "State"),
        ("cidr", "CIDR"),
        ("ipv6_cidr_blocks", "IPv6 prefixes"),
        ("subnet_access", "Subnet access"),
        ("vcn_id", "VCN"),
        ("created", "Created"),
    ],
    "core.images": [
        ("name", "Name"),
        ("state", "State"),
        ("os", "OS"),
        ("os_version", "OS version"),
        ("size_gb", "Size(GB)"),
        ("created", "Created"),
    ],
    "core.platform-images": [
        ("name", "Name"),
        ("state", "State"),
        ("os", "OS"),
        ("os_version", "OS version"),
        ("size_gb", "Size(GB)"),
        ("created", "Created"),
    ],
    "core.custom-images": [
        ("name", "Name"),
        ("state", "State"),
        ("base_image", "Original image"),
        ("size_gb", "Billable size(GB)"),
        ("created", "Created"),
    ],
    "core.route-rules": [
        ("destination", "Destination"),
        ("destination_type", "Destination type"),
        ("network_entity_id", "Target"),
        ("route_type", "Route type"),
        ("description", "Description"),
    ],
    "core.security-list-rules": [
        ("direction", "Direction"),
        ("protocol", "Protocol"),
        ("source", "Source"),
        ("destination", "Destination"),
        ("description", "Description"),
    ],
    "core.cpes": [
        ("name", "Name"),
        ("ip_address", "IP"),
        ("cpe_device_shape_id", "Device shape"),
        ("created", "Created"),
    ],
    "core.ip_sec_connections": [
        ("name", "Name"),
        ("state", "State"),
        ("cpe_id", "CPE"),
        ("drg_id", "DRG"),
        ("created", "Created"),
    ],
    "core.private_ips": [
        ("name", "IP"),
        ("state", "State"),
        ("hostname_label", "Hostname"),
        ("is_primary", "Primary"),
        ("lifetime", "Lifetime"),
        ("vnic_id", "VNIC"),
        ("created", "Created"),
    ],
    "core.vnic_attachments": [
        ("name", "OCID"),
        ("state", "State"),
        ("instance_id", "Instance"),
        ("subnet_id", "Subnet"),
        ("vnic_id", "VNIC"),
        ("created", "Created"),
    ],
    "core.volume_attachments": [
        ("name", "OCID"),
        ("state", "State"),
        ("instance_id", "Instance"),
        ("device", "Device"),
        ("volume_id", "Volume"),
        ("is_read_only", "Read only"),
        ("created", "Created"),
    ],
    "core.boot_volume_attachments": [
        ("name", "OCID"),
        ("state", "State"),
        ("instance_id", "Instance"),
        ("boot_volume_id", "Boot volume"),
        ("display_name", "Name"),
        ("created", "Created"),
    ],
    "core.drg_attachments": [
        ("name", "Name"),
        ("state", "State"),
        ("drg_id", "DRG"),
        ("vcn_id", "VCN"),
        ("network_details_type", "Attachment type"),
        ("created", "Created"),
    ],
    "core.network_security_group_security_rules": [
        ("name", "OCID"),
        ("direction", "Direction"),
        ("protocol", "Protocol"),
        ("source", "Source"),
        ("destination", "Destination"),
    ],
    "core.drg_route_rules": [
        ("destination", "Destination"),
        ("route_type", "Route type"),
        ("next_hop_drg_attachment_id", "Next hop"),
        ("description", "Description"),
    ],
    "core.fast_connect_provider_services": [
        ("provider_name", "Provider"),
        ("provider_service_name", "Service"),
        ("state", "State"),
        ("supported_virtual_circuit_types", "VC types"),
        ("created", "Created"),
    ],
    "core.public_ips": [
        ("ip_address", "IP"),
        ("state", "State"),
        ("public_ip_pool_id", "Pool"),
        ("lifetime", "Lifetime"),
        ("private_ip", "Private IP"),
        ("created", "Created"),
    ],
    "core.public_ip_pools": [
        ("name", "Name"),
        ("state", "State"),
        ("created", "Created"),
    ],
    "core.cross_connect_groups": [
        ("name", "Name"),
        ("state", "State"),
        ("created", "Created"),
    ],
    "core.cross_connects": [
        ("name", "Name"),
        ("state", "State"),
        ("location_name", "Location"),
        ("port_name", "Port"),
        ("bandwidth_shape_name", "Bandwidth"),
        ("created", "Created"),
    ],
    "core.dhcp_options": [
        ("name", "Name"),
        ("state", "State"),
        ("vcn_id", "VCN"),
        ("created", "Created"),
    ],
    "core.services": [
        ("name", "Name"),
        ("cidr_block", "CIDR"),
        ("description", "Description"),
    ],
    "core.remote_peering_connections": [
        ("name", "Name"),
        ("state", "State"),
        ("drg_id", "DRG"),
        ("created", "Created"),
    ],
    "core.volumes": [
        ("name", "Name"),
        ("state", "State"),
        ("size_gb", "Size(GB)"),
        ("vpus_per_gb", "VPU/GB"),
        ("availability_domain", "Availability domain"),
        ("volume_group_id", "Volume group"),
        ("created", "Created"),
    ],
    "core.boot_volumes": [
        ("name", "Name"),
        ("state", "State"),
        ("size_gb", "Size(GB)"),
        ("vpus_per_gb", "VPU/GB"),
        ("availability_domain", "Availability domain"),
        ("created", "Created"),
    ],
    "core.volume_groups": [
        ("name", "Name"),
        ("state", "State"),
        ("size_gb", "Size(GB)"),
        ("volume_count", "Volumes"),
        ("created", "Created"),
    ],
    "core.volume_backups": [
        ("name", "Name"),
        ("state", "State"),
        ("size_gb", "Size(GB)"),
        ("type", "Type"),
        ("volume_id", "Volume"),
        ("created", "Created"),
    ],
    "core.boot_volume_backups": [
        ("name", "Name"),
        ("state", "State"),
        ("size_gb", "Size(GB)"),
        ("type", "Type"),
        ("boot_volume_id", "Boot volume"),
        ("created", "Created"),
    ],
    "core.volume_group_backups": [
        ("name", "Name"),
        ("state", "State"),
        ("size_gb", "Size(GB)"),
        ("type", "Type"),
        ("volume_group_id", "Volume group"),
        ("created", "Created"),
    ],
    "core.block_volume_replicas": [
        ("name", "Name"),
        ("state", "State"),
        ("size_gb", "Size(GB)"),
        ("volume_id", "Volume"),
        ("availability_domain", "Availability domain"),
        ("created", "Created"),
    ],
    "core.boot_volume_replicas": [
        ("name", "Name"),
        ("state", "State"),
        ("size_gb", "Size(GB)"),
        ("boot_volume_id", "Boot volume"),
        ("availability_domain", "Availability domain"),
        ("created", "Created"),
    ],
    "dns.zones": [
        ("name", "Name"),
        ("state", "State"),
        ("scope", "Scope"),
        ("zone_type", "Zone type"),
        ("view_id", "View"),
        ("created", "Created"),
    ],
    "dns.zone_transfer_servers": [
        ("name", "Name"),
        ("state", "State"),
        ("address", "Address"),
        ("created", "Created"),
    ],
    "dns.resolvers": [
        ("name", "Name"),
        ("state", "State"),
        ("view_id", "View"),
        ("created", "Created"),
    ],
    "dns.resolver_endpoints": [
        ("name", "Name"),
        ("state", "State"),
        ("endpoint_type", "Endpoint type"),
        ("address", "Address"),
        ("created", "Created"),
    ],
    "dns.views": [("name", "Name"), ("state", "State"), ("created", "Created")],
    "dns.tsig_keys": [("name", "Name"), ("state", "State"), ("created", "Created")],
    "dns.steering_policies": [
        ("name", "Name"),
        ("state", "State"),
        ("template", "Template"),
        ("created", "Created"),
    ],
    "dns.steering_policy_attachments": [
        ("name", "Name"),
        ("state", "State"),
        ("zone_id", "Zone"),
        ("domain_name", "Domain"),
        ("steering_policy_id", "Policy"),
        ("created", "Created"),
    ],
    "dns.zone-records": [
        ("domain", "Domain"),
        ("rtype", "Type"),
        ("ttl", "TTL"),
        ("is_protected", "Protected"),
        ("rdata", "RData"),
    ],
    "identity.compartments": [
        ("name", "Name"),
        ("state", "State"),
        ("description", "Description"),
        ("ocid", "OCID"),
    ],
    "identity.users": [
        ("name", "Name"),
        ("state", "State"),
        ("email", "Email"),
        ("email_verified", "Email verified"),
        ("is_mfa_activated", "MFA"),
        ("created", "Created"),
    ],
    "identity.groups": [
        ("name", "Name"),
        ("state", "State"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "identity.dynamic_groups": [
        ("name", "Name"),
        ("state", "State"),
        ("matching_rule", "Matching rule"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "identity.policies": [
        ("name", "Name"),
        ("state", "State"),
        ("statement_count", "Statements"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "identity.tag_namespaces": [
        ("name", "Name"),
        ("state", "State"),
        ("is_retired", "Retired"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "identity.tags": [
        ("name", "Name"),
        ("state", "State"),
        ("is_cost_tracking", "Cost tracking"),
        ("is_retired", "Retired"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "identity.network_sources": [
        ("name", "Name"),
        ("state", "State"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "identity.domains": [
        ("display_name", "Name"),
        ("state", "State"),
        ("home_region", "Home region"),
        ("license_type", "License"),
        ("created", "Created"),
    ],
    "identity.availability_domains": [
        ("name", "Name"),
        ("state", "State"),
        ("created", "Created"),
    ],
    "identity.fault_domains": [
        ("name", "Name"),
        ("availability_domain_name", "Availability domain"),
        ("compartment_id", "Compartment"),
    ],
    "identity.regions": [("name", "Name"), ("key", "Key")],
    "identity.region_subscriptions": [
        ("region_name", "Region"),
        ("region_key", "Key"),
        ("status", "Status"),
        ("is_home_region", "Home"),
    ],
    "identity.iam_work_requests": [
        ("name", "Name"),
        ("state", "State"),
        ("operation_type", "Operation"),
        ("resource_type", "Resource"),
        ("timestamp", "Timestamp"),
    ],
    "identity.iam_work_request_logs": [
        ("timestamp", "Timestamp"),
        ("message", "Message"),
    ],
    "identity.iam_work_request_errors": [
        ("timestamp", "Timestamp"),
        ("code", "Code"),
        ("message", "Message"),
    ],
    "identity.user_group_memberships": [
        ("name", "Name"),
        ("state", "State"),
        ("user_id", "User"),
        ("group_id", "Group"),
        ("created", "Created"),
    ],
    "identity.api_keys": [
        ("fingerprint", "Fingerprint"),
        ("state", "State"),
        ("user_id", "User"),
        ("created", "Created"),
    ],
    "identity.auth_tokens": [
        ("description", "Description"),
        ("state", "State"),
        ("user_id", "User"),
        ("time_expires", "Expires"),
        ("created", "Created"),
    ],
    "identity.customer_secret_keys": [
        ("name", "Name"),
        ("state", "State"),
        ("user_id", "User"),
        ("created", "Created"),
    ],
    "identity.db_credentials": [
        ("name", "Name"),
        ("state", "State"),
        ("user_id", "User"),
        ("created", "Created"),
    ],
    "identity.mfa_totp_devices": [
        ("name", "Name"),
        ("state", "State"),
        ("user_id", "User"),
        ("created", "Created"),
    ],
    "identity.o_auth_client_credentials": [
        ("name", "Name"),
        ("state", "State"),
        ("user_id", "User"),
        ("created", "Created"),
    ],
    "identity.smtp_credentials": [
        ("description", "Description"),
        ("state", "State"),
        ("user_id", "User"),
        ("created", "Created"),
    ],
    "identity.swift_passwords": [
        ("description", "Description"),
        ("state", "State"),
        ("user_id", "User"),
        ("expires_on", "Expires"),
        ("created", "Created"),
    ],
    "orm.stacks": [
        ("display_name", "Name"),
        ("state", "State"),
        ("terraform_version", "TF version"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "orm.jobs": [
        ("display_name", "Name"),
        ("state", "State"),
        ("operation", "Operation"),
        ("stack_id", "Stack"),
        ("time_finished", "Finished"),
        ("created", "Created"),
    ],
    "orm.private_endpoints": [
        ("display_name", "Name"),
        ("state", "State"),
        ("vcn_id", "VCN"),
        ("dns_zone_count", "DNS zones"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "orm.templates": [
        ("display_name", "Name"),
        ("state", "State"),
        ("is_free_tier", "Free tier"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "orm.configuration_source_providers": [
        ("display_name", "Name"),
        ("state", "State"),
        ("config_source_provider_type", "Type"),
        ("is_migration_required", "Migration"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "orm.work_requests": [
        ("name", "Name"),
        ("state", "State"),
        ("operation_type", "Operation"),
        ("percent_complete", "%"),
        ("timestamp", "Timestamp"),
    ],
    "orm.template_categories": [("display_name", "Name"), ("name", "ID")],
    "orm.terraform_versions": [("name", "Version"), ("is_default", "Default")],
    "orm.resource_discovery_services": [("name", "Name"), ("discovery_scope", "Scope")],
    "orm.stack_associated_resources": [
        ("resource_name", "Name"),
        ("resource_type", "Type"),
        ("region", "Region"),
        ("resource_address", "Address"),
        ("resource_id", "Resource"),
        ("created", "Created"),
    ],
    "orm.stack_resource_drift_details": [
        ("resource_name", "Name"),
        ("resource_type", "Type"),
        ("resource_drift_status", "Drift"),
        ("stack_id", "Stack"),
        ("time_drift_checked", "Checked"),
    ],
    "orm.job_associated_resources": [
        ("resource_name", "Name"),
        ("resource_type", "Type"),
        ("region", "Region"),
        ("resource_address", "Address"),
        ("resource_id", "Resource"),
        ("created", "Created"),
    ],
    "orm.job_outputs": [
        ("output_name", "Name"),
        ("output_type", "Type"),
        ("is_sensitive", "Sensitive"),
        ("output_value", "Value"),
        ("description", "Description"),
    ],
    "orm.work_request_logs": [("timestamp", "Timestamp"), ("message", "Message")],
    "orm.work_request_errors": [
        ("timestamp", "Timestamp"),
        ("code", "Code"),
        ("message", "Message"),
    ],
    "load_balancer.load_balancers": [
        ("name", "Name"),
        ("state", "State"),
        ("overall_health", "Overall health"),
        ("is_private", "Private"),
        ("ip_addresses", "IP addresses"),
        ("shape_name", "Shape"),
        ("created", "Created"),
    ],
    "containerengine.clusters": [
        ("name", "Name"),
        ("state", "State"),
        ("kubernetes_version", "K8s"),
        ("cluster_type", "Type"),
        ("vcn_id", "VCN"),
        ("private_endpoint", "Private endpoint"),
        ("created", "Created"),
    ],
    "containerengine.node_pools": [
        ("name", "Name"),
        ("state", "State"),
        ("kubernetes_version", "K8s"),
        ("node_shape", "Node shape"),
        ("ocpus", "OCPU"),
        ("memory_gb", "Memory(GB)"),
        ("node_count", "Nodes"),
        ("node_image_name", "Node image"),
        ("created", "Created"),
    ],
    "containerengine.virtual_node_pools": [
        ("name", "Name"),
        ("state", "State"),
        ("kubernetes_version", "K8s"),
        ("cluster_id", "Cluster"),
        ("created", "Created"),
    ],
    "containerengine.addon_options": [
        ("name", "Name"),
        ("state", "State"),
        ("kubernetes_version", "K8s"),
        ("created", "Created"),
    ],
    "containerengine.addons": [
        ("name", "Name"),
        ("state", "State"),
        ("description", "Description"),
        ("created", "Created"),
    ],
    "containerengine.pod_shapes": [
        ("name", "Name"),
        ("state", "State"),
        ("ocpus", "OCPU"),
        ("memory_gb", "Memory(GB)"),
        ("created", "Created"),
    ],
    "containerengine.virtual_nodes": [
        ("name", "Name"),
        ("state", "State"),
        ("private_ip", "Private IP"),
        ("subnet_id", "Subnet"),
        ("created", "Created"),
    ],
    "containerengine.work_requests": [
        ("name", "Name"),
        ("state", "State"),
        ("operation_type", "Operation"),
        ("resource_type", "Resource"),
        ("percent_complete", "%"),
        ("cluster_id", "Cluster"),
        ("timestamp", "Timestamp"),
    ],
    "containerengine.work_request_logs": [
        ("timestamp", "Timestamp"),
        ("message", "Message"),
    ],
    "containerengine.work_request_errors": [
        ("timestamp", "Timestamp"),
        ("code", "Code"),
        ("message", "Message"),
    ],
    "containerengine.workload_mappings": [
        ("name", "Name"),
        ("state", "State"),
        ("cluster_id", "Cluster"),
        ("description", "Description"),
        ("created", "Created"),
    ],
}

GENERIC_COLUMN_LABELS = {
    "scope_type": "Scope",
    "value": "Value",
    "are_quotas_supported": "Quotas",
    "is_eligible_for_limit_increase": "Increase eligible",
    "cidr": "CIDR",
    "cidr_block": "CIDR",
    "dns_label": "DNS label",
    "availability_domain": "Availability domain",
    "fault_domain": "Fault domain",
    "shape": "Shape",
    "size_gb": "Size(GB)",
    "vcn_id": "VCN",
    "subnet_id": "Subnet",
    "vnic_id": "VNIC",
    "drg_id": "DRG",
    "network_entity_id": "Target",
    "next_hop_drg_attachment_id": "Next hop",
    "cpe_id": "CPE",
    "public_ip": "Public IP",
    "private_ip": "Private IP",
    "ip_address": "IP",
    "ip_addresses": "IP addresses",
    "ipv6_cidr_block": "IPv6 prefix",
    "ipv6_cidr_blocks": "IPv6 prefixes",
    "display_name": "Name",
    "hostname_label": "Hostname",
    "is_primary": "Primary",
    "is_protected": "Protected",
    "lifetime": "Lifetime",
    "location_name": "Location",
    "port_name": "Port",
    "domain": "Domain",
    "rtype": "Type",
    "ttl": "TTL",
    "rdata": "RData",
    "scope": "Scope",
    "zone_type": "Zone type",
    "view_id": "View",
    "resolver_id": "Resolver",
    "zone_id": "Zone",
    "steering_policy_id": "Policy",
    "domain_name": "Domain",
    "template": "Template",
    "address": "Address",
    "endpoint_type": "Endpoint type",
    "direction": "Direction",
    "protocol": "Protocol",
    "device": "Device",
    "boot_volume_id": "Boot volume",
    "volume_id": "Volume",
    "volume_group_id": "Volume group",
    "vpus_per_gb": "VPU/GB",
    "volume_count": "Volumes",
    "type": "Type",
    "is_read_only": "Read only",
    "network_details_type": "Attachment type",
    "route_type": "Route type",
    "ocpus": "OCPU",
    "memory_gb": "Memory(GB)",
    "bandwidth_shape": "Bandwidth",
    "bandwidth_shape_name": "Bandwidth",
    "storage_size_gb": "Storage(GB)",
    "is_ipv6_enabled": "IPv6",
    "route_rules": "Routes",
    "security_rules": "Rules(i/e)",
    "attachments": "Attached",
    "destination": "Destination",
    "destination_type": "Destination type",
    "source_type": "Source type",
    "gateway_type": "Gateway type",
    "kubernetes_version": "K8s",
    "cluster_type": "Type",
    "message": "Message",
    "code": "Code",
    "timestamp": "Timestamp",
    "operation_type": "Operation",
    "resource_type": "Resource",
    "percent_complete": "%",
    "private_endpoint": "Private endpoint",
    "public_endpoint": "Public endpoint",
    "node_shape": "Node shape",
    "cluster_id": "Cluster",
    "node_count": "Nodes",
    "subnet_count": "Subnets",
    "node_image_name": "Node image",
    "description": "Description",
    "created": "Created",
    "terraform_version": "TF version",
    "operation": "Operation",
    "time_finished": "Finished",
    "dns_zone_count": "DNS zones",
    "config_source_provider_type": "Type",
    "is_migration_required": "Migration",
    "discovery_scope": "Scope",
    "resource_name": "Name",
    "resource_address": "Address",
    "resource_id": "Resource",
    "resource_drift_status": "Drift",
    "time_drift_checked": "Checked",
    "region": "Region",
    "output_name": "Name",
    "output_type": "Type",
    "is_sensitive": "Sensitive",
    "output_value": "Value",
}

# Address allocation and reachability are mandatory defaults whenever present.
ADDRESS_COLUMN_PRIORITY = [
    "cidr",
    "cidr_block",
    "ipv6_cidr_blocks",
    "ipv6_cidr_block",
    "private_ip",
    "public_ip",
    "ip_addresses",
    "ip_address",
]

GENERIC_COLUMN_PRIORITY = [
    *ADDRESS_COLUMN_PRIORITY,
    "dns_label",
    "availability_domain",
    "shape",
    "size_gb",
    "vcn_id",
    "subnet_id",
    "vnic_id",
    "drg_id",
    "network_entity_id",
    "next_hop_drg_attachment_id",
    "public_ip",
    "private_ip",
    "ip_address",
    "display_name",
    "hostname_label",
    "is_primary",
    "is_protected",
    "lifetime",
    "location_name",
    "port_name",
    "domain",
    "rtype",
    "ttl",
    "rdata",
    "scope",
    "zone_type",
    "view_id",
    "resolver_id",
    "zone_id",
    "steering_policy_id",
    "domain_name",
    "template",
    "address",
    "endpoint_type",
    "direction",
    "protocol",
    "device",
    "boot_volume_id",
    "volume_id",
    "volume_group_id",
    "vpus_per_gb",
    "volume_count",
    "type",
    "is_read_only",
    "network_details_type",
    "route_type",
    "bandwidth_shape",
    "bandwidth_shape_name",
    "storage_size_gb",
    "route_rules",
    "security_rules",
    "attachments",
    "destination",
    "destination_type",
    "source_type",
    "gateway_type",
    "kubernetes_version",
    "cluster_type",
    "message",
    "code",
    "timestamp",
    "operation_type",
    "resource_type",
    "percent_complete",
    "node_shape",
    "node_count",
    "node_image_name",
    "cluster_id",
    "private_endpoint",
    "public_endpoint",
    "description",
    "created",
    "terraform_version",
    "operation",
    "time_finished",
    "dns_zone_count",
    "config_source_provider_type",
    "is_migration_required",
    "discovery_scope",
    "resource_name",
    "resource_address",
    "resource_id",
    "resource_drift_status",
    "time_drift_checked",
    "region",
    "output_name",
    "output_type",
    "is_sensitive",
    "output_value",
]

COLUMN_MINIMUMS = {
    "qualified_name": 18,
    "client_name": 12,
    "list_operation": 18,
    "endpoint_family": 8,
    "scope": 10,
    "runnable": 8,
    "name": 12,
    "state": 8,
    "public_ip": 12,
    "private_ip": 12,
    "shape": 16,
    "display_name": 14,
    "direction": 9,
    "protocol": 8,
    "device": 10,
    "boot_volume_id": 18,
    "volume_id": 18,
    "is_read_only": 9,
    "network_details_type": 16,
    "ocpus": 4,
    "memory_gb": 10,
    "availability_domain": 18,
    "fault_domain": 12,
    "created": 19,
    "cidr": 14,
    "dns_label": 10,
    "is_ipv6_enabled": 4,
    "base_image": 24,
    "size_gb": 8,
    "kubernetes_version": 8,
    "cluster_type": 14,
    "private_endpoint": 18,
    "public_endpoint": 18,
    "node_shape": 18,
    "cluster_id": 18,
    "node_count": 5,
    "subnet_count": 7,
    "node_image_name": 20,
    "default_route_table_id": 18,
    "default_security_list_id": 18,
    "vcn_id": 18,
    "subnet_id": 18,
    "vnic_id": 18,
    "drg_id": 18,
    "network_entity_id": 18,
    "next_hop_drg_attachment_id": 18,
    "prohibit_public_ip_on_vnic": 12,
    "hostname_label": 16,
    "is_primary": 7,
    "lifetime": 10,
    "route_type": 10,
    "message": 20,
    "code": 10,
    "timestamp": 19,
    "operation_type": 16,
    "resource_type": 12,
    "percent_complete": 4,
    "description": 20,
    "ocid": 18,
}

DIRECT_GETTERS = {
    "compartment": ("identity", "get_compartment"),
    "instance": ("compute", "get_instance"),
    "cpe": ("virtual_network", "get_cpe"),
    "crossconnect": ("virtual_network", "get_cross_connect"),
    "crossconnectgroup": ("virtual_network", "get_cross_connect_group"),
    "dhcpoptions": ("virtual_network", "get_dhcp_options"),
    "vcn": ("virtual_network", "get_vcn"),
    "subnet": ("virtual_network", "get_subnet"),
    "vnic": ("virtual_network", "get_vnic"),
    "drg": ("virtual_network", "get_drg"),
    "drgattachment": ("virtual_network", "get_drg_attachment"),
    "routetable": ("virtual_network", "get_route_table"),
    "securitylist": ("virtual_network", "get_security_list"),
    "natgateway": ("virtual_network", "get_nat_gateway"),
    "servicegateway": ("virtual_network", "get_service_gateway"),
    "internetgateway": ("virtual_network", "get_internet_gateway"),
    "localpeeringgateway": ("virtual_network", "get_local_peering_gateway"),
    "networksecuritygroup": ("virtual_network", "get_network_security_group"),
    "vlan": ("virtual_network", "get_vlan"),
    "publicip": ("virtual_network", "get_public_ip"),
    "publicippool": ("virtual_network", "get_public_ip_pool"),
    "remotepeeringconnection": ("virtual_network", "get_remote_peering_connection"),
    "volume": ("blockstorage", "get_volume"),
    "volumebackup": ("blockstorage", "get_volume_backup"),
    "volumegroup": ("blockstorage", "get_volume_group"),
    "volumegroupbackup": ("blockstorage", "get_volume_group_backup"),
    "bootvolume": ("blockstorage", "get_boot_volume"),
    "bootvolumebackup": ("blockstorage", "get_boot_volume_backup"),
    "volumereplica": ("blockstorage", "get_block_volume_replica"),
    "bootvolumereplica": ("blockstorage", "get_boot_volume_replica"),
    "loadbalancer": ("load_balancer", "get_load_balancer"),
    "networkfirewall": ("network_firewall", "get_network_firewall"),
    "networkfirewallpolicy": ("network_firewall", "get_network_firewall_policy"),
    "zone": ("dns", "get_zone"),
    "resolver": ("dns", "get_resolver"),
    "view": ("dns", "get_view"),
    "tsigkey": ("dns", "get_tsig_key"),
    "steeringpolicy": ("dns", "get_steering_policy"),
    "steeringpolicyattachment": ("dns", "get_steering_policy_attachment"),
    "user": ("identity", "get_user"),
    "group": ("identity", "get_group"),
    "dynamicgroup": ("identity", "get_dynamic_group"),
    "policy": ("identity", "get_policy"),
    "tagnamespace": ("identity", "get_tag_namespace"),
    "identitynetworksource": ("identity", "get_network_source"),
    "domain": ("identity", "get_domain"),
    "iamworkrequest": ("identity", "get_iam_work_request"),
    "image": ("compute", "get_image"),
    "cluster": ("container_engine", "get_cluster"),
    "nodepool": ("container_engine", "get_node_pool"),
    "virtualnodepool": ("container_engine", "get_virtual_node_pool"),
    "workrequest": ("container_engine", "get_work_request"),
    "ormstack": ("resource_manager", "get_stack"),
    "ormjob": ("resource_manager", "get_job"),
    "ormprivateendpoint": ("resource_manager", "get_private_endpoint"),
    "ormtemplate": ("resource_manager", "get_template"),
    "ormconfigsourceprovider": (
        "resource_manager",
        "get_configuration_source_provider",
    ),
    "ormworkrequest": ("resource_manager", "get_work_request"),
}
